[2024-10-21T04:03:58.135+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-21T04:03:58.157+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_csv_to_mongo.insert_data_to_mongo manual__2024-10-21T04:03:54.239450+00:00 [queued]>
[2024-10-21T04:03:58.166+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_csv_to_mongo.insert_data_to_mongo manual__2024-10-21T04:03:54.239450+00:00 [queued]>
[2024-10-21T04:03:58.167+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-21T04:03:58.189+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): insert_data_to_mongo> on 2024-10-21 04:03:54.239450+00:00
[2024-10-21T04:03:58.196+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=139) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-21T04:03:58.198+0000] {standard_task_runner.py:72} INFO - Started process 141 to run task
[2024-10-21T04:03:58.199+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'insert_csv_to_mongo', 'insert_data_to_mongo', 'manual__2024-10-21T04:03:54.239450+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag_save_mongodb.py', '--cfg-path', '/tmp/tmp336bltly']
[2024-10-21T04:03:58.202+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask insert_data_to_mongo
[2024-10-21T04:03:58.262+0000] {task_command.py:467} INFO - Running <TaskInstance: insert_csv_to_mongo.insert_data_to_mongo manual__2024-10-21T04:03:54.239450+00:00 [running]> on host 04f7c4f1243c
[2024-10-21T04:03:58.374+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='insert_csv_to_mongo' AIRFLOW_CTX_TASK_ID='insert_data_to_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T04:03:54.239450+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-21T04:03:54.239450+00:00'
[2024-10-21T04:03:58.376+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-21T04:03:58.410+0000] {logging_mixin.py:190} INFO - Erro: Arquivo n√£o encontrado. Detalhes: [Errno 2] No such file or directory: 'D:\\AIRFLOW_CHECKPOINT\\Checkpoint5e6profTiago.csv'
[2024-10-21T04:03:58.410+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-21T04:03:58.421+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-21T04:03:58.422+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=insert_csv_to_mongo, task_id=insert_data_to_mongo, run_id=manual__2024-10-21T04:03:54.239450+00:00, execution_date=20241021T040354, start_date=20241021T040358, end_date=20241021T040358
[2024-10-21T04:03:58.457+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-21T04:03:58.476+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-21T04:03:58.479+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
