[2024-09-28T20:17:18.011+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-28T20:17:18.026+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alagamentos_dag.extrair_inserir_alagamentos scheduled__2024-01-01T13:00:00+00:00 [queued]>
[2024-09-28T20:17:18.032+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alagamentos_dag.extrair_inserir_alagamentos scheduled__2024-01-01T13:00:00+00:00 [queued]>
[2024-09-28T20:17:18.033+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-28T20:17:18.044+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extrair_inserir_alagamentos> on 2024-01-01 13:00:00+00:00
[2024-09-28T20:17:18.050+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=137) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-28T20:17:18.051+0000] {standard_task_runner.py:72} INFO - Started process 174 to run task
[2024-09-28T20:17:18.052+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'alagamentos_dag', 'extrair_inserir_alagamentos', 'scheduled__2024-01-01T13:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/alagamentos_dag.py', '--cfg-path', '/tmp/tmpimnwhpe_']
[2024-09-28T20:17:18.053+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask extrair_inserir_alagamentos
[2024-09-28T20:17:18.098+0000] {task_command.py:467} INFO - Running <TaskInstance: alagamentos_dag.extrair_inserir_alagamentos scheduled__2024-01-01T13:00:00+00:00 [running]> on host 8e572da5f6fc
[2024-09-28T20:17:18.216+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alagamentos_dag' AIRFLOW_CTX_TASK_ID='extrair_inserir_alagamentos' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T13:00:00+00:00'
[2024-09-28T20:17:18.219+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-28T20:17:18.225+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-28T20:17:18.227+0000] {logging_mixin.py:190} INFO - Current task name:extrair_inserir_alagamentos state:running start_date:2024-09-28 20:17:18.026536+00:00
[2024-09-28T20:17:18.231+0000] {logging_mixin.py:190} INFO - Dag name:alagamentos_dag and current dag run status:running
[2024-09-28T20:17:18.234+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-28T20:17:18.499+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/alagamentos_dag.py", line 28, in extrair_e_inserir_dados
    ultima_data = obter_ultima_data(conn)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/alagamentos_dag.py", line 18, in obter_ultima_data
    cursor.execute("SELECT MAX(dt_data) FROM T_SKT_ALAGAMENTOS")
  File "/home/airflow/.local/lib/python3.12/site-packages/oracledb/cursor.py", line 710, in execute
    impl.execute(self)
  File "src/oracledb/impl/thin/cursor.pyx", line 196, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src/oracledb/impl/thin/protocol.pyx", line 440, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 441, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 433, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/messages.pyx", line 74, in oracledb.thin_impl.Message._check_and_raise_exception
oracledb.exceptions.DatabaseError: ORA-00942: table or view does not exist
Help: https://docs.oracle.com/error-help/db/ora-00942/
[2024-09-28T20:17:18.512+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-28T20:17:18.512+0000] {logging_mixin.py:190} INFO - Task start:2024-09-28 20:17:18.026536+00:00 end:2024-09-28 20:17:18.511637+00:00 duration:0.485101
[2024-09-28T20:17:18.513+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extrair_inserir_alagamentos> dag:<DAG: alagamentos_dag> dagrun:<DagRun alagamentos_dag @ 2024-01-01 13:00:00+00:00: scheduled__2024-01-01T13:00:00+00:00, state:running, queued_at: 2024-09-28 20:17:16.338805+00:00. externally triggered: False>
[2024-09-28T20:17:18.513+0000] {logging_mixin.py:190} INFO - Failure caused by ORA-00942: table or view does not exist
Help: https://docs.oracle.com/error-help/db/ora-00942/
[2024-09-28T20:17:18.514+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=alagamentos_dag, task_id=extrair_inserir_alagamentos, run_id=scheduled__2024-01-01T13:00:00+00:00, execution_date=20240101T130000, start_date=20240928T201718, end_date=20240928T201718
[2024-09-28T20:17:18.525+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-28T20:17:18.525+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 76 for task extrair_inserir_alagamentos (ORA-00942: table or view does not exist
Help: https://docs.oracle.com/error-help/db/ora-00942/; 174)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/alagamentos_dag.py", line 28, in extrair_e_inserir_dados
    ultima_data = obter_ultima_data(conn)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/alagamentos_dag.py", line 18, in obter_ultima_data
    cursor.execute("SELECT MAX(dt_data) FROM T_SKT_ALAGAMENTOS")
  File "/home/airflow/.local/lib/python3.12/site-packages/oracledb/cursor.py", line 710, in execute
    impl.execute(self)
  File "src/oracledb/impl/thin/cursor.pyx", line 196, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src/oracledb/impl/thin/protocol.pyx", line 440, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 441, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 433, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/messages.pyx", line 74, in oracledb.thin_impl.Message._check_and_raise_exception
oracledb.exceptions.DatabaseError: ORA-00942: table or view does not exist
Help: https://docs.oracle.com/error-help/db/ora-00942/
[2024-09-28T20:17:18.550+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-28T20:17:18.557+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
